version: '3.8'
services:
  postgres:
    container_name: db-service  # Nome personalizzato per il container PostgreSQL
    build:
      context: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: cas2023
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  backend:
    container_name: backend  # Nome personalizzato per il container del backend
    build:
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app # Percorso del codice sorgente del backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres  # Il servizio "backend" dipende dal servizio "postgres"

  frontend:
    container_name: frontend  # Nome personalizzato per il container del backend
    build:
      context: ./frontend
    volumes:
      - /app/node_modules # Corretto il percorso dei node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend  # Il servizio "frontend" dipende dal servizio "backend"