version: '3'
services:
  postgres:
    container_name: db  # Nome personalizzato per il container PostgreSQL
    image: postgis/postgis:12-3.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Mp090998
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  backend:
    container_name: backend  # Nome personalizzato per il container del backend
    build:
      context: ./backend
      dockerfile: dockerfile.dev # Assicurati che il Dockerfile sia nella directory ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app # Percorso del codice sorgente del backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres  # Il servizio "backend" dipende dal servizio "postgres"

  frontend:
    container_name: frontend  # Nome personalizzato per il container del backend
    build:
      context: ./frontend
      dockerfile: dockerfile.dev # Assicurati che il Dockerfile sia nella directory ./frontend
    volumes:
      - /app/node_modules # Corretto il percorso dei node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend  # Il servizio "frontend" dipende dal servizio "backend"
